<?xml version="1.0"?>
<!--
Copyright (c) 2013, Goncalo Cabrita, ISR University of Coimbra
Copyright (c) 2015 Clearpath Robotics
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Clearpath Robotics nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="laser_diam" value="0.080" />
  <xacro:property name="laser_h" value="0.185" />
  <xacro:property name="laser_mass" value="3.3" />

  <xacro:macro name="box_inertial" params="x y z mass">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0" 
        iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0" 
        izz="${0.0833333 * mass * (x*x + y*y)}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sick_s3000_mount" params="prefix topic">
    <link name="${prefix}_laser_mount">
      <!-- TODO: replace with sick_s3000 visual -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://j5_description/meshes/sick-lms1xx-bracket.stl" />
        </geometry>
        <material name="dark_grey" />
      </visual>
    </link> 

    <link name="${prefix}_laser">
      <xacro:box_inertial x="${laser_diam}" y="${laser_diam}" z="${laser_h}" mass="${laser_mass}" />
      <!-- TODO: replace with sick_s3000 visual -->
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!-- Origin of this mesh is the focal point of the LIDAR. -->
          <mesh filename="package://j5_description/meshes/sick-lms1xx.stl" />
        </geometry>
        <material name="light_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${laser_diam} ${laser_diam} ${laser_h}" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_laser_joint" type="fixed">
      <!-- This offset is from the base of the bracket to the LIDAR's focal point. -->
      <!-- TODO: replace origin with proper measurement for sick_s3000 -->
      <origin xyz="0 0 0.149" rpy="0 0 0" />
      <!--origin xyz="${laser_diam/2} 0 0" rpy="0 0 0" /-->
      <parent link="${prefix}_laser_mount" />
      <child link="${prefix}_laser" />
    </joint>

    <gazebo reference="${prefix}_laser">
      <material>Gazebo/Yellow</material>
      <turnGravityOff>true</turnGravityOff>
      <sensor type="ray" name="${prefix}_laser">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>40</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-1.658</min_angle>
              <max_angle>1.658</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.10</min>
            <max>30.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.001</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
          <topicName>${topic}</topicName>
          <frameName>${prefix}_laser</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>
</robot>
