%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-warthog-control
Version:        0.1.4
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS warthog_control package

License:        BSD
URL:            http://www.clearpathrobotics.com/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-controller-manager
Requires:       ros-noetic-diff-drive-controller
Requires:       ros-noetic-interactive-marker-twist-server
Requires:       ros-noetic-joint-state-controller
Requires:       ros-noetic-joy
Requires:       ros-noetic-robot-localization
Requires:       ros-noetic-teleop-twist-joy
Requires:       ros-noetic-topic-tools
Requires:       ros-noetic-twist-mux
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-roslaunch
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Controllers for Warthog

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Nov 11 2021 Tony Baltovski <tbaltovski@clearpathrobotics.com> - 0.1.4-1
- Autogenerated by Bloom

