warthog_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

warthog_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['fl_wheel_jnt', 'bl_wheel_jnt']
  right_wheel: ['fr_wheel_jnt', 'br_wheel_jnt']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation: 1.08 # Auto read will fail due to suspension link
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 5.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 50.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 40.0   # rad/s^2

ekf_localization:
  frequency: 50
  odom0: /warthog_velocity_controller/odom
  odom0_config: [true, true, false,
                 false, false, true,
                 true, true, false,
                 false, false, true]
  odom0_differential: false
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  two_d_mode: true
