topics:
- name    : rc
  topic   : rc_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 8
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 6
- name    : other
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
